### ISSUE TITLE
Mobiles with gomobile

### ISSUE THREAD

**Issue by gedw99** [src-d/go-mysql-server#198] opened 2018-05-20 19:10 UTC
This is great. Anyone know if this runs embedded on mobile ?
Will be much easier to manage that sqlite !

**Comment by smola** [comment] 2018-05-21 12:57
@gedw99 Note that go-mysql-server does not compete with sqlite. Both by design and by current project status.

The main design difference is that go-mysql-server is not a full-blown database. It is a storage-independent engine. **go-mysql-server does not provide a storage backend** (other than an in-memory one that we use for testing). If you want to read persisted data, you need to provide your own storage implementation. The storage backend could be CSV or sqlite itself.

On the current status of the project:

1. We do not support as many SQL features as sqlite.
2. INSERT/UPDATE queries are quite limited, we are focused on SELECT queries.
3. Our performance probably doesn't even come close to sqlite.

That being said, we'll appreciate help from the community on getting it to work with gomobile. It is something we don't plan to do ourselves in the short term though.

**Comment by gedw99** [comment] 2018-05-22 19:50
thanks for the thought rundown on the scope.

I can have a go at go at getting it working. first i need to work out
though how to have a backing store.
I am guessing that FK are not supported for updates and so the data is
really held as denormalised data ? Once i know this is makes it much easier
to see what backing store would be appropropriate

**Comment by smola** [comment] 2018-05-23 07:41
@gedw99 Right. Primary keys, foreign keys or any other constraint is not supported yet. UPDATE is not supported yet either, only INSERT.

In our primary use case (i.e. [gitbase](https://github.com/src-d/gitbase)) we never write data, only read data that already exists in the backend. So INSERT has just been used for convenience during testing with the in-memory backend.

In the [mem](https://github.com/src-d/go-mysql-server/tree/master/mem) package you have an in-memory backend that you can use for testing, or to check how to implement a new one.

**Comment by gedw99** [comment] 2018-05-23 07:48
@smola thanks - its clear. Its weird though. Why not just use a KV store then since thats all your needing. Its not trolling... just curious. I guess the answer is that you want to make it a sql store and started with what you needed for now.

**Comment by smola** [comment] 2018-05-23 10:48
@gedw99 Our goal is providing a SQL interface that people is familiar with. It's not just "KV" stuff, but joins, group by, order by, subqueries, expressions, etc. The project is intentionally not implementing storage in the core, and probably never will, since we are not trying to build a database, just a SQL interface for arbitrary storage backends.

**Comment by gedw99** [comment] 2018-05-24 04:56
ok got it ! makes it clear what the intent is. thanks.

This is quite cool.

**Comment by ajnavarro** [comment] 2018-07-05 08:44
Closing this as resolved. @gedw99 if you have any other question, don't hesitate to do it.

**Closed by ajnavarro** 2018-07-05 08:44 UTC
Labels: enhancement
