### ISSUE TITLE
sleep function cannot be cancelled

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#797] opened 2019-08-07 15:10 UTC
we are just calling to time.Sleep, and that cannot be canceled from the Context. Change sleep to make it cancellable.

**Comment by juanjux** [comment] 2019-08-07 16:18
Easy way to reproduce: `select sleep(1000)` and control-C.

**Comment by creachadair** [comment] 2019-08-07 16:50
This should do it:

```go
// sleepContext sleeps for the specified duration or until ctx ends, and reports
// whether the sleep ended due to context cancellation.
func sleepContext(ctx context.Context, dur time.Duration) bool {
  select {
  case <-time.After(dur):
    return false
  case <-ctx.Done():
    return true
  }
}
```

Note that after the context ends the timer will run to completion before it will be GC'd. If that matters you can do something more explicit with `time.NewTimer`. But in general that is probably safe unless you start a lot of these and they run for a long time.

**Comment by juanjux** [comment] 2019-08-07 17:08
Already fixed, forgot to close this :)

**Comment by juanjux** [comment] 2019-08-07 17:10
Your solution is better since the fact that the After already is interrupted if ctx is Done went over me, I'm updating the PR, thanks!

**Closed** 2019-08-08 09:44 UTC
Labels: bug
