### ISSUE TITLE
Feature request: don't die on panic

### ISSUE THREAD

**Issue by smacker** [src-d/go-mysql-server#625] opened 2019-02-22 10:17 UTC
It would be nice to wrap query handler in `defer recover()` so in case a query panics it would return an error to the client instead of server exiting.

Similar to how it usually works with http servers:
```go
func(w http.ResponseWriter, r *http.Request) {
	defer func() {
		if rp := recover(); rvr != nil {
			log.Error("panic %v", rp)
			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		}
	}()

	next.ServeHTTP(w, r) // actual handler
}
```

**Comment by creachadair** [comment] 2019-02-25 16:08
Be careful about swallowing panics high up in the call stack. You may avert a process termination, but generally the heap is now in an unknown and generally invalid state. You are likely to resume only to crash again later much further away from the original problem, and it is _very_ hard to debug these.

As a rule, try to avoid handing panics that you didn't throw. If code indirects a nil pointer or reads off the end of a slice, the program is _broken_, and crashing is actually preferable. Otherwise the experience for the user is potentially much worse: It could lead to weird data corruptions, broken transactions, and other infelicities.  I mention this because I've had to debug this, and it's much worse than the problem it is meant to solve IMO.

**Comment by erizocosmico** [comment] 2019-02-25 17:01
As @creachadair says, I'd rather catch the panic earlier and have a proper stack trace than keep it running potentially incorrectly.

**Comment by kuba--** [comment] 2019-02-25 19:48
We already have the main `recover` mechanism as a listener's handler (implemented by vitess).
Of course, adding another one to every go routine does not make sense. On the other hand, root cause analysis showed that go-git's object lru cache may panic.
I'm totally against implementing recover on the cache level (in my opinion it should be fixed).

I'm not a big fan of `recover` in defers, so the question is - how do we plan to solve this mystery (@ajnavarro, @smola), because based on my analysis `func (it *exchangeRowIter) iterPartition(p sql.Partition)` looks like a place between internals and session.

Personally I would do nothing (so far), just integrate go-git with @jfontan 's fix: https://github.com/src-d/go-git/pull/1076 and monitor situation if something like that happen again.

**Comment by ajnavarro** [comment] 2019-02-26 08:42
So right now the problem is on partitions.
I think if we panic in one of the partitions, we should stop the whole query. this will mimic the previous query behavior without parallelization. Problems related with inconsistencies should be minimal. WDYT?

**Comment by creachadair** [comment] 2019-02-26 15:30
> So right now the problem is on partitions.
> 
> I think if we panic in one of the partitions, we should stop the whole query. this will mimic the previous query behavior without parallelization. Problems related to inconsistencies should be minimal. WDYT?

Using a panic to handle a controlled unwinding event—e.g., a parse or query that fails deep inside, and where the only thing you need to do is get control back to the top so you can report and resume—seems like a reasonable use. I'd generally advise defining your own panic signal type, e.g.

```go
type queryFailed string

…
// hypothetical interface, I have no idea what the real API looks like.
func query(ctx context.Context, q *Query) (_ *Result, err error) {
   defer func() {
      if x := recover(); x != nil {
         if s, ok := x.(queryFailed); ok {
            err = errors.New(s)
         } else {
            panic(x)
         }
      }
   }()
   return q.Run(ctx, new(Result)) // whatever
}
```

or words to that effect. That way you only get the panic you care about.

**Comment by kuba--** [comment] 2019-02-27 11:55
@creachadair - what you proposed, is what we already have (by vitess).
Now we need something similar for partition iterators (go routines, so you cannot catch them on the main thread). Moreover it's hard to define _panic interface_, because we don't panic on purpose. 
What I propose: https://github.com/src-d/go-mysql-server/pull/626 is just a simple `recover` in already existing defer which closes all iterators and appends recovery error to _error channel_.
So, the outside process can receive an error and follow an error scenario.

**Comment by creachadair** [comment] 2019-02-27 14:51
> @creachadair - what you proposed, is what we already have (by vitess).

As I understand it, Vitess made the same mistake that a lot of HTTP implementations do: It logs and swallows _any_ panic, not just controlled ones.

> Now we need something similar for partition iterators (go routines, so you cannot catch them on the main thread). Moreover it's hard to define _panic interface_, because we don't panic on purpose.

Right, and that's specifically _not_ the kind of panic I'm talking about. That's a program integrity violation, and swallowing that panic will leave the heap in a corrupt state with unknown future effects.

> What I propose: #626 is just a simple `recover` in already existing defer which closes all iterators and appends recovery error to _error channel_.
> So, the outside process can receive an error and follow an error scenario.

Obviously it's not my decision, but I would not recommend this approach at all. I don't know what the trigger for these panics is, but swallowing them isn't going to prevent the program from being broken, but will only change _where_ it breaks (and perhaps make it less obvious).

**Comment by kuba--** [comment] 2019-02-27 22:50
Personally I think in case of partition iterator it should be fine if we just close the iterator. The only concern I have is the fact that `recover` will stop stack unwinding.
@ajnavarro - so maybe if we catch a panic we'll restart mysql process by sending _a user specific sygnal_. Here is a simple prototype:

```go
func foo() {
	defer func() {
		if x := recover(); x != nil {
			fmt.Println("recover:", x)
			syscall.Kill(syscall.Getpid(), syscall.SIGUSR2)
		}
	}()

	panic("foo")
}

func fork() {
	exe, _ := os.Executable()
	dir := filepath.Dir(exe)

	// Spawn child process.
	os.StartProcess(exe, []string{exe}, &os.ProcAttr{
		Dir: dir,
		Files: []*os.File{
			os.Stdin,
			os.Stdout,
			os.Stderr,
		},
		Sys: &syscall.SysProcAttr{},
	})
}

func main() {	
	signalCh := make(chan os.Signal, 1)
	signal.Notify(signalCh, syscall.SIGUSR2)

	go foo()

	for {
		select {
		case s := <-signalCh:
			fork()
			return
		}
	}
}
```

Let me know what do you think.

**Comment by creachadair** [comment] 2019-02-27 23:06
If you don't want to stop unwinding, you can just panic again in the handler:

```
if x := recover(); x != nil {
   cleanup(whatever)
   panic(x)  // resume panicking
}
```

maybe that helps simplify things a bit?

**Closed** 2019-03-11 12:27 UTC
Labels: proposal
